### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by rashil2000** [Elvyria/wcolor#3]
Hey!

A few months ago I was searching for commandline color pickers for Windows, because the popular utility [pastel](https://github.com/sharkdp/pastel) requires one. The only ones I could find were GUI pickers, which I listed here - https://github.com/sharkdp/pastel/issues/150

Because they're GUI pickers, they can't report the picked color back to the calling application.

wcolor solves this problem nicely. It provides a picker and writes the color to stdout. Thanks for making this!

So I want to ask if it fine to add picking support to pastel on Windows, utilizing wcolor.

**Comment by rashil2000** [comment]
Also, would it be possible to modify preview window size and scale? The movement of preview window is pretty smooth for me (as opposed to #1), but since I have a big monitor it appears quite small.

**Comment by Elvyria** [comment]
Yes it's okay for third party tools to utilize wcolor. This project, apart from solving the color picking issue, was also meant as educational resource for other people to learn how to utilize WinAPI and Direct2D in rust, and so it has MIT license.

About the resolution scaling issue, hmm... i don't have experience writing scaling code for different resolutions, but hard-coded values for 1080p are [here](https://github.com/Elvyria/wcolor/blob/6dfb3e859d7dd3afcf6c33f2809221e5d65a8f50/src/preview.rs#L128) and [here](https://github.com/Elvyria/wcolor/blob/6dfb3e859d7dd3afcf6c33f2809221e5d65a8f50/src/preview.rs#L158). If you want to add some form of scaling or just command line arguments to change size, feel free to open PR. I'll also take a look at scaling subject, but i can't make you any promises.

**Comment by rashil2000** [comment]
Thank you for the response!

I'll see what I can come up (I have very little experience with either Rust on WinAPI).

**Comment by Elvyria** [comment]
I added an option to modify preview size. Not sure if it's a good enough solution for bigger resolutions, HDPI or whatnot. If it doesn't fully suffice, feel free to open another issue with description.

Version is updated. Corresponding commits: d1025290f68890dba737d1754cf7bfca43170dff a36ad2e5afb9da9db4f17975ab4eb21b9ffb1f4b

**Comment by rashil2000** [comment]
Hi!

Yes, the new option works perfect, thanks!
